import type { Metadata } from "next";
import { Geist, Geist_Mono, Abril_Fatface } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav-bar";
import BackToTopArrow from "@/components/back-to-top-arrow";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const abrilFatface = Abril_Fatface({
  variable: "--font-abril-fatface",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "The Syntax",
  description: "Generated by create next app",
  openGraph: {
    title: "The Syntax",
    description: "A modern Next.js application",
    type: "website",
    url: "https://yourdomain.com",
  },
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${abrilFatface.variable} antialiased`}
      >
        <div className="max-w-screen min-h-screen overflow-hidden bg-black">
          <NavBar />
          {children}
        </div>
        <BackToTopArrow />
      </body>
    </html>
  );
}
